sudo: false

language: go
arch:
  - amd64
  - s390x
  - arm64
os: linux
go:
  - 1.14.x
env:
  - K8S_VERSION=v1.18.0
services:
  - docker
script:
- mkdir -p ~/gopath/src/sigs.k8s.io/
- hack/verify-vendor.sh
- make build
- make push
